# GenerateWord1Spec.cmake
#
# Transform MKCMD's opuscmd_native.inc (MSVC #pragma comment(linker,"/export:X")
# lines) into a winebuild .spec that exports the same symbols from the Winelib
# WORD1 module.  Same source of truth as the MSVC /export list: one name per
# unique command/EL entry point (427 names).
#
# Invoked as:
#   cmake -DINPUT=.../opuscmd_native.inc -DOUTPUT=.../word1.spec -P GenerateWord1Spec.cmake

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "GenerateWord1Spec.cmake requires -DINPUT= and -DOUTPUT=")
endif()

if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "GenerateWord1Spec.cmake: INPUT does not exist: ${INPUT}")
endif()

file(STRINGS "${INPUT}" _lines)
set(_body "")
set(_count 0)
foreach(_line IN LISTS _lines)
    # #pragma comment(linker, "/export:CmdHelp")
    if(_line MATCHES "#pragma[ \t]+comment\\([ \t]*linker[ \t]*,[ \t]*\"/export:([A-Za-z_][A-Za-z0-9_]*)\"[ \t]*\\)")
        set(_name "${CMAKE_MATCH_1}")
        # cdecl: matches the C definitions in the engine archive (no stdcall
        # decoration).  On x86-64 Wine the calling convention token is mostly
        # a name-export vehicle for GetProcAddress.
        string(APPEND _body "@ cdecl ${_name}()\n")
        math(EXPR _count "${_count} + 1")
    endif()
endforeach()

if(_count EQUAL 0)
    message(FATAL_ERROR
        "GenerateWord1Spec.cmake: no /export: lines found in ${INPUT}")
endif()

set(_header
"# Auto-generated by GenerateWord1Spec.cmake from opuscmd_native.inc.
# Do not edit.  Regenerated when MKCMD rewrites the native command table.
# ${_count} exports for ResolveCommandAddress / GetProcAddress.
#
")
file(WRITE "${OUTPUT}" "${_header}${_body}")
message(STATUS "GenerateWord1Spec: wrote ${_count} exports to ${OUTPUT}")
